qdrant:
  path_to_qdrant_collection: "../data/langchain_qdrant_10percent"
  embedder_model_name: "sergeyzh/rubert-tiny-turbo"
  collection_name: "embed_collection_10percent"
llm:
  ollama_model_name: "herenickname/t-tech_T-lite-it-1.0:q4_k_m"
  temperature: 0.2
  base_url: "http://localhost:11434"
streamlit:
  api_answer_link: "http://127.0.0.1:8000/rag-answer"