version: '3.8'

services:
  rag-service:
    build:
      context: ./src
      dockerfile: Dockerfile.rag
    container_name: rag-service
    ports:
      - "8000:8000"
    depends_on:
      - streamlit
    volumes:
      - ./data:/app/data
    environment:
      - OLLAMA_HOST_FROM_CONTAINER=http://host.docker.internal:11434
      - DATA_PATH=/app/data

  streamlit:
    build:
      context: ./ui
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      RAG_API_URL: http://rag-service:8000/rag-answer
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DATABASE_URL: ${DATABASE_URL}

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-init:
    build:
      context: ./init_db
      dockerfile: Dockerfile.init
    container_name: postgres-init
    depends_on:
      - postgres
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

volumes:
  postgres_data:
  