FROM python:3.10-slim

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/ui

WORKDIR /app/ui

COPY ../config.yaml /app/config.yaml

CMD ["streamlit", "run", "full_app.py", "--server.port=8501", "--server.address=0.0.0.0"]